spring:
  application:
    name: university-service
  datasource:
    url: jdbc:mysql://localhost:3306/MyCompany
    username: root
    password: password

server:
  port: 7900

logging:
  level:
    root: info


eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  #indicates the frequency the client sends heartbeat to server to indicate that it is alive.
  instance:
    lease-renewal-interval-in-seconds: 30